# Generated by Django 4.1 on 2022-08-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripeId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptionId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
